name: Build and Publish

on:
  workflow_dispatch:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build
        uses: ./.github/actions/build
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          perform_deploy: ${{ github.ref == 'refs/heads/master' || github.ref == 'refs/heads/waterdog-2' }}
          deploy_repository: "waterdog-snapshots"
          deploy_username: ${{ secrets.DEPLOY_USERNAME }}
          deploy_password: ${{ secrets.DEPLOY_PASSWORD }}
          create_prerelease: ${{ github.ref == 'refs/heads/master' }}
          prerelease_name: "latest"

      - name: Docker Login
        uses: docker/login-action@v1
        with:
          registry: "ghcr.io"
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: "ghcr.io/${{ github.repository }}"
          tags: |
            type=raw,value=latest,enable=${{ github.ref == format('refs/heads/{0}', 'master') }}

      - name: Docker build and push
        id: docker_build
        uses: docker/build-push-action@v4
        with:
          context: .
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
